FROM docker.io/redhat/ubi9:latest
ADD sample.txt /
ADD --keep-git-dir https://github.com/kiranpanchavati9/learn-docker.git /
ADD --unpack=true https://roboshop-artifacts.s3.amazonaws.com/frontend.zip /

